## Numpy is a python library
15/10/25

In [1]:
#show array
import numpy

arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
#numpy is usually imported under the np allas or allias (check)
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
#Checking numpy version
print(np.__version__)

2.1.3


In [13]:
#0-D array
import numpy as np

arr = np.array(42)
print(arr)

42


In [6]:
#1-D array
import numpy

arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [12]:
#2-D array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [16]:
#check number of dimensions
import numpy as np

a=np.array(42)
b=np.array([1,2,3,4])
c=np.array([[1,2,3,4],[5,6,7,8]])
d=np.array([[1,2,3,4],[5,6,7,8],[12,13,14,15]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
2


In [21]:

import numpy as np

arr = np.array([1,2,3,4,5], ndmin =5)
print(arr)
print("number of dimension is :", arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimension is : 5


In [ ]:
somethin

In [22]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("2nd element of first row", arr[0,1])


2nd element of first row 2


In [24]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("2nd element of first row", arr[1,3])

IndexError: index 3 is out of bounds for axis 1 with size 3

In [29]:
#append()
import numpy 
a = numpy.array([[1,2,3],[4,5,6]])
b = numpy.array([[400],[800]])
newArray = numpy.append(a, b, axis =1)
print(newArray)

[[  1   2   3 400]
 [  4   5   6 800]]
