## Numpy is a python library
15/10/25

In [1]:
#show array
import numpy

arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
#numpy is usually imported under the np allas or allias (check)
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
#Checking numpy version
print(np.__version__)

2.1.3


In [30]:
#Checking numpy version
print(numpy.__version__)

2.1.3


In [13]:
#0-D array
import numpy as np

arr = np.array(42)
print(arr)

42


In [6]:
#1-D array
import numpy

arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [12]:
#2-D array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [31]:
#3-D array
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[12,13,14]])
print(arr)


[[ 1  2  3]
 [ 4  5  6]
 [12 13 14]]


In [32]:
#check number of dimensions
import numpy as np

a=np.array(42)
b=np.array([1,2,3,4])
c=np.array([[1,2,3,4],[5,6,7,8]])
d=np.array([[[1,2,3,4],[5,6,7,8]],[[12,13,14,15],[1,2,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [21]:

import numpy as np

arr = np.array([1,2,3,4,5], ndmin =5)
print(arr)
print("number of dimension is :", arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimension is : 5


In [33]:
arr=np.array([1,2,3,4])
print(arr[1])

2


In [22]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("2nd element of first row", arr[0,1])


2nd element of first row 2


In [34]:
#addition within array
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [36]:
#loop within array
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("5th element of 2nd row", arr[1,4]) #1 represent 2nd row and 4 represent 5th element

5th element of first row 10


In [37]:
#append()
import numpy 
a = numpy.array([[1,2,3],[4,5,6]])
b = numpy.array([[400],[800]])
newArray = numpy.append(a, b, axis =1)
print(newArray)

[[  1   2   3 400]
 [  4   5   6 800]]


In [41]:
# np.nditer() is a NumPy iterator that allows you to loop through every element in an array one by one, no matter the shape.
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]):  # : select all rows ::2 take every second column (step 2)

1
3
5
7


In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3) # 4 numb  of row , 3 numb of column
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
#convert 1-D into 3-D
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [6]:
#show numb of row and column
import numpy 
arr = numpy.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [8]:

import numpy as np

arr = np.array([1,2,3,4], ndmin =5)
print(arr)
print("shape of array :", arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [10]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [11]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [13]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [14]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [15]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [16]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [17]:

import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4]) 

[7 8 9]


In [18]:

import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2]) 

[3 8]


In [19]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])  # 0:2 first row -- 1:4 second row

[[2 3 4]
 [7 8 9]]


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [22]:
import numpy as np

arr = np.array(["banana", "orange", "mango"])
print(arr)
print(arr.dtype)

['banana' 'orange' 'mango']
<U6
